// Generated by CoffeeScript 1.12.6
var Env;

Env = (function() {
  function Env(opts) {
    if (opts == null) {
      opts = {
        a: 0,
        d: 0,
        s: 1,
        r: 0
      };
    }
    if (opts.a == null) {
      opts.a = 0;
    }
    if (opts.a < 0) {
      opst.a = 0;
    }
    if (typeof opts.a !== 'number') {
      throw new Error('Attack must be numeric');
    }
    this.a = opts.a;
    if (opts.d == null) {
      opts.d = 0;
    }
    if (opts.d < 0) {
      opts.d = 0;
    }
    if (typeof opts.d !== 'number') {
      throw new Error('Decay must be numeric');
    }
    this.d = opts.d;
    if (opts.s == null) {
      opts.s = 1;
    }
    if (typeof opts.s !== 'number') {
      throw new Error('Sustain must be numeric');
    }
    this.s = opts.s;
    if (opts.r == null) {
      opts.r = 0;
    }
    if (opts.r < 0) {
      opts.r = 0;
    }
    if (typeof opts.r !== 'number') {
      throw new Error('Release must be numeric');
    }
    this.r = opts.r;
  }

  Env.prototype.tf = function(t) {
    if ((0 <= t && t < this.a)) {
      return t / this.a;
    } else if ((this.a <= t && t < this.a + this.d)) {
      return (t - this.a) * (this.s - 1) / this.d + 1;
    } else {
      return this.s;
    }
  };

  return Env;

})();

module.exports = Env;
