// Generated by CoffeeScript 1.12.6
var Gain;

Gain = (function() {
  function Gain(opts) {
    if (!(opts && opts.signal)) {
      throw new Error('Missing Signal');
    }
    if (!opts.signal.tf()) {
      throw new Error('Signal must be a TFC');
    }
    this.signal = opts.signal;
  }

  return Gain;

})();

module.exports = Gain;
