// Generated by CoffeeScript 1.12.6
var Harm;

Harm = (function() {
  function Harm(opts) {
    if (!opts) {
      throw new Error('Missing Options');
    }
    if (!opts.osc) {
      throw new Error('Missing Oscillator');
    }
    if (!((opts.osc.freq != null) && (opts.osc.tf != null))) {
      throw new Error('osc must be an Osc');
    }
    this.osc = opts.osc;
  }

  return Harm;

})();

module.exports = Harm;
