// Generated by CoffeeScript 1.12.6
var Harm;

Harm = (function() {
  function Harm(opts) {
    if (!(opts && opts.osc && opts.osc.freq && (opts.osc.tf != null))) {
      throw new Error('Missing Oscillator');
    }
    this.osc = osc;
  }

  return Harm;

})();
